### ISSUE TITLE
Move to anaconda GitHub org

### ISSUE THREAD

**Issue by jezdez** [anaconda/anaconda-anon-usage#6]
It would be better to have this repo in the main anaconda org to reduce the sprawl. /cc @bandwidthninja

**Comment by jezdez** [comment]
I've filed ticket TRK-8344 internally to make this happen.

**Comment by slickrik** [comment]
Hey @jezdez I've transferred this to the Anaconda org and permissions were retained. I did add the devops team as an admin on the repo as well.
